//! Parse iptables LOG entries for "blocked packet" UX.
//!
//! Pipeline:
//!   1. Every DROP rule (system-generated by aeon-net-services.sh OR
//!      user-created via /api/firewall/rules) goes through the
//!      `AEON_DROP` chain, which LOGs (rate-limited) before dropping.
//!   2. The kernel writes a single line per logged packet to the
//!      system journal, prefixed with "AEON-DROP: ", in iptables'
//!      classic key=value format: IN=usb0 OUT= MAC=... SRC=10.55.0.10
//!      DST=8.8.8.8 LEN=... PROTO=UDP SPT=12345 DPT=53
//!   3. On GET, we run `journalctl -k --since "-2h" --grep "AEON-DROP:"`
//!      and parse each line. Cheap (one shell-out per request); the
//!      journal already does the heavy lifting + retention.
//!
//! The UI shows recent entries with an "Allow this traffic" button per
//! row that links to /network with a pre-populated firewall rule form.

use crate::api::AppState;
use axum::extract::{Query, State};
use axum::Json;
use serde::Deserialize;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::process::Command;

#[derive(Deserialize, Default)]
pub struct BlockedQuery {
    /// Max entries to return (1..1000). Default 300 — enough to spot a
    /// recent pattern, small enough to render fast.
    #[serde(default)]
    pub limit: Option<usize>,
}

/// GET /api/security/blocked
pub async fn list(
    State(_state): State<AppState>,
    Query(q): Query<BlockedQuery>,
) -> Json<Value> {
    let limit = q.limit.unwrap_or(300).clamp(1, 1000);

    // Pull last ~2 hours from the kernel journal. journalctl supports
    // a grep filter natively which is much cheaper than reading the
    // whole journal and filtering client-side.
    //
    // Match "AEON-DROP" without the trailing colon — v39+ extended the
    // prefix to "AEON-DROP[<tag>]: " with a bracketed tag so we can
    // attribute drops to a specific rule. v37-era "AEON-DROP: " (no
    // tag) still matches this prefix too, so existing post-upgrade
    // entries don't disappear.
    let output = tokio::task::spawn_blocking(move || {
        Command::new("journalctl")
            .args([
                "-k",
                "--since", "-2h",
                "--grep", "AEON-DROP",
                "-o", "short-iso",
                "--no-pager",
                // Cap the journalctl tail so a chatty hour doesn't blow
                // RAM. We want at most a few thousand lines to scan.
                "-n", "5000",
            ])
            .output()
    })
    .await;

    let text = match output {
        Ok(Ok(o)) => String::from_utf8_lossy(&o.stdout).to_string(),
        _ => String::new(),
    };

    let mut entries: Vec<Value> = Vec::with_capacity(limit);
    for line in text.lines().rev() {
        if let Some(parsed) = parse_log_line(line) {
            entries.push(parsed);
            if entries.len() >= limit {
                break;
            }
        }
    }
    Json(json!({
        "ok": true,
        "entries": entries,
        "since": "-2h",
    }))
}

/// Parse one journalctl line into a structured entry. Returns None if
/// the line doesn't look like an AEON-DROP entry.
///
/// The log prefix is `AEON-DROP[<tag>]: ` where <tag> identifies the
/// rule that dropped the packet — vpn-udp-forward, usbnet-iso-rfc1918,
/// fw-<id> for user rules, etc. blocked_log surfaces the tag so the
/// UI can show "Blocked by: <human-readable>" + link to the rule.
fn parse_log_line(raw: &str) -> Option<Value> {
    let drop_idx = raw.find("AEON-DROP")?;
    let after_prefix = &raw[drop_idx + "AEON-DROP".len()..];

    // Read the optional [tag] portion.
    let (cause_tag, body) = if let Some(after_lbracket) = after_prefix.strip_prefix('[') {
        match after_lbracket.find("]:") {
            Some(end) => (
                after_lbracket[..end].to_string(),
                &after_lbracket[end + 2..], // skip "]:"
            ),
            None => (String::new(), after_prefix),
        }
    } else {
        // v37 and earlier used "AEON-DROP: " with no tag. Keep parsing
        // those entries so the panel doesn't go blank right after an
        // upgrade.
        (String::new(), after_prefix)
    };

    // Timestamp is the first whitespace-separated token on the line.
    let ts_ms = raw
        .split_whitespace()
        .next()
        .and_then(parse_iso8601_ms)
        .unwrap_or(0);

    // Parse key=value tokens. iptables emits empty values too (OUT= MAC=).
    let mut fields: HashMap<&str, &str> = HashMap::new();
    for tok in body.split_whitespace() {
        if let Some((k, v)) = tok.split_once('=') {
            fields.insert(k, v);
        }
    }

    let proto = fields.get("PROTO").copied().unwrap_or("").to_string();
    let src = fields.get("SRC").copied().unwrap_or("").to_string();
    let dst = fields.get("DST").copied().unwrap_or("").to_string();
    let in_if = fields.get("IN").copied().unwrap_or("").to_string();
    let out_if = fields.get("OUT").copied().unwrap_or("").to_string();
    let spt = fields.get("SPT").copied().unwrap_or("").to_string();
    let dpt = fields.get("DPT").copied().unwrap_or("").to_string();
    let length = fields
        .get("LEN")
        .and_then(|v| v.parse::<u64>().ok())
        .unwrap_or(0);

    Some(json!({
        "ts_ms": ts_ms,
        "cause_tag": cause_tag,
        "in_iface": in_if,
        "out_iface": out_if,
        "proto": proto,
        "src": src,
        "dst": dst,
        "sport": spt,
        "dport": dpt,
        "length": length,
    }))
}

/// Parse "YYYY-MM-DDTHH:MM:SS±HHMM" → epoch millis. Same code as in
/// dns_log.rs but duplicated to keep modules independent. Dead-simple,
/// dependency-free.
fn parse_iso8601_ms(s: &str) -> Option<i64> {
    let core = s.get(0..19)?;
    let mut it = core.split(|c| c == '-' || c == 'T' || c == ':');
    let y: i64 = it.next()?.parse().ok()?;
    let mo: i64 = it.next()?.parse().ok()?;
    let d: i64 = it.next()?.parse().ok()?;
    let h: i64 = it.next()?.parse().ok()?;
    let mi: i64 = it.next()?.parse().ok()?;
    let se: i64 = it.next()?.parse().ok()?;
    let y = y - if mo <= 2 { 1 } else { 0 };
    let era = if y >= 0 { y } else { y - 399 } / 400;
    let yoe = y - era * 400;
    let doy = (153 * (if mo > 2 { mo - 3 } else { mo + 9 }) + 2) / 5 + d - 1;
    let doe = yoe * 365 + yoe / 4 - yoe / 100 + doy;
    let days = era * 146_097 + doe - 719_468;
    let unix_secs = days * 86_400 + h * 3600 + mi * 60 + se;
    let mut offset_min: i64 = 0;
    if s.len() >= 24 {
        let off = &s[19..];
        let sign: i64 = if off.starts_with('+') { -1 }
                        else if off.starts_with('-') { 1 }
                        else { 0 };
        if sign != 0 {
            let cleaned: String = off[1..].chars().filter(|c| c.is_ascii_digit()).collect();
            if cleaned.len() >= 4 {
                let oh: i64 = cleaned[..2].parse().unwrap_or(0);
                let om: i64 = cleaned[2..4].parse().unwrap_or(0);
                offset_min = sign * (oh * 60 + om);
            }
        }
    }
    Some((unix_secs + offset_min * 60) * 1000)
}
